#!/usr/bin/env bash
#Script that copies a file to the server using scp

if [[ $# < 3 ]] ; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 3 parameters passed"
else
	sudo scp -C -i $4 -r $1 $3@$2:~/
fi
