#!/usr/bin/env bash
#script to configure nginx

sudo apt-get install -y nginx
new_string="server_name _;\n\tlocation \/redirect_me{\n\t\treturn 301 https:\/\/www.youtube.com\/;\n\t}"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default
sudo service nginx restart
