#!/usr/bin/env bash
# A script that configure nginx http response header

sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html

new_string="server_name _;\n\tlocation \/redirect_me{\n\t\treturn 301 https:\/\/www.youtube.com\/;\n\t}"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

sudo touch /usr/share/nginx/html/4-not_found_page_404.html
echo "Ceci n'est pas une page<br/>" | sudo tee /usr/share/nginx/html/4-not_found_page_404.html
new_string="server_name _;\n\n\terror_page 404 \/4-not_found_page_404.html;\n\tlocation = \/4-not_found_page_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

hostname="[0-9]+-web-[0-9]+"
ip_address=$(grep -E "$hostname" /etc/hosts | awk '{print $3}')
new_string="server_name _;\n\n\tadd_header X-Served-By \"$ip_address\";"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

sudo service nginx restart
