#!/usr/bin/env bash
# The story of /etc/passwd

while read -r line
do
	USERNAME=$(cut -d ":" -f 1 <<< "$line")
	GROUP_ID=$(cut -d ":" -f 2 <<< "$line")
	HOME_DIRECTORY=$(cut -d ":" -f 3 <<< "$line")
	CSHELL=$(cut -d ":" -f 4 <<< "$line")
	ID=$(cut -d ":" -f 5 <<< "$line")
	PASSWORD=$(cut -d ":" -f 6 <<< "$line")
	INFO=$(cut -d ":" -f 7 <<< "$line")
	echo "The user $USERNAME is part of the $CSHELL gang, lives in $PASSWORD and rides $INFO. $HOME_DIRECTORY's place is protected by the passcode $GROUP_ID, more info about the user here: $ID"
done < /etc/passwd
