#!/usr/bin/env bash
# A script to display "Best School using a while loop"

iter=1
while [ $iter -lt 21 ]
do
	echo "$iter"
case $iter in
	4)
		echo "bad luck from China";;
	9)
		echo "bad luck from Japan";;
	17)
		echo "bad luck from Italy";;
esac
iter=$(( iter+1 ))
done
