#!/usr/bin/env bash
# A script that checks the status of a file

if [ -e "$1" ]; then
	echo "school file exists"
	if [ ! -s "$1" ]; then
		echo "school file is empty"
	elif [ -s "$1" ]; then
		echo "school file is not empty"
	fi
	if [ -f "$1" ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
