#!/usr/bin/env bash
#Bash script to change the IP addresses of localhost nd facebook.com
cp /etc/hosts ~/hosts.new
sudo sed -i 's/127\.0\.0\.2\s\+localhost/127.0.0.1 localhost/' ~/hosts.new
echo "8.8.8.8 facebook.com" > ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
