#!/usr/bin/env bash
# Script that changes my ubuntu server

cp /etc/hosts ~hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
hosts.new
cp -f ~/hosts.new /etc/hosts
